---
name: "clean_cache_rule"
pack: "monitor_test"
description: "Rule to clean cache when needed"
enabled: true
trigger:
  type: "monitor_test.cache_cleanup_needed"
criteria: {}
action:
  ref: "monitor_test.clean_cache"
  parameters: {}
