---  
name: "clean_cache_rule"  
description: "Rule untuk membersihkan cache jika diperlukan."  
enabled: true  
trigger:  
  type: "advanced_monitoring.cache_cleanup_needed"  
action:  
  ref: "advanced_monitoring.clean_cache"  
  parameters:  
    cache_type: "{{ trigger.cache_type }}"  