---
name: "notify_critical_alert"
description: "Notifikasi untuk alert kritis."
enabled: true
trigger:
  type: "monitor_test.critical_alert"
action:
  ref: "monitor_test.notify_discord"
  parameters:
    webhook_url: "{{ config.webhook_url }}"
    message: "Critical alert detected: Type - {{ trigger.type }}, Value - {{ trigger.value }}."
