name: "restart_container_rule"
description: "Restart container jika gagal berjalan."
enabled: true
trigger:
  type: "monitor_test.container_failed"
action:
  ref: "monitor_test.restart_container"
  parameters:
    container_id: "{{ trigger.container_id }}"
