---
name: "restart_container_rule"
pack: "monitor_test"
description: "Restart container if it fails."
enabled: true
trigger:
  type: "monitor_test.container_failed"
action:
  ref: "monitor_test.restart_container"
  parameters:
    container_id: "{{ trigger.container_id }}"
